name: first workflow
on:
  push:
    branches:
      - developer
jobs:
  example-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "Hello again!"
      - name: checkout 
        uses: actions/checkout@v6.0.0
      - name: list dir
        run: ls -la

